### PR TITLE
Update cargo.toml

### PR DESCRIPTION
**Pull request by Hoverbear**
Now successfully builds, also uses a binary project instead of a library, since this is intended to scaffold a web app.

### CODE REVIEW

**Comment by Hoverbear** [comment]
@untitaker  / @SkylerLipthay Can you +1 this?

**Comment by untitaker** [comment]
I'm unclear about the future of this module. Perhaps we should kill it off for
now and revive it when its dependencies hit 1.0. Then we don't need to use
wildcard version specifiers either.

**Comment by Hoverbear** [comment]
@untitaker Well, we can't delete the repository. I suppose @reem could.

**Comment by SkylerLipthay** [comment]
I have a history of telling people that this crate is dead... and I do recall reem confirming that.

But if it does live, maybe `params` belongs too :)

**Comment by Hoverbear** [comment]
Then it should be remove from [here](https://github.com/iron/iron#core-extensions), [here](https://github.com/iron/router#overview) etc.

**Pull request closed without merging**
