### PR TITLE
Link to new crate for static files

### PR DESCRIPTION
**Pull request by EduardoBautista**

### CODE REVIEW

**Comment by EduardoBautista** [comment]
Should I also update the `Cargo.toml`?

**Comment by reem** [comment]
Please do! You'll likely need a corresponding change in src/lib.rs

**Comment by EduardoBautista** [comment]
Doesn't look like it's even in the `src/lib.rs` file to begin with.

**Comment by reem** [comment]
Well, that's an oversight. Can you add it?

**Pull request merged**
